makefile:

CC = gcc
CFLAGS = -Wall -Wextra -g


CLIENT_EXEC = exec/Client
CLIENT_OBJ = obj/Client.o 
CLIENT_SRC = client.c

SERVER_EXEC = exec/Server
SERVER_OBJ = obj/Server.o 
SERVER_SRC = server.c

TESTS_OBJ = AudioTest.o GDBTest.o FDTest.o
TESTS_SRC = AudioTest.c GDBTest.c FDTest.c
TESTS_HDR = AudioTest.h GDBTest.h FDTest.h


EXEC = $(CLIENT_EXEC) $(SERVER_EXEC)


all: $(EXEC) 

$(CLIENT_EXEC): $(CLIENT_OBJ) 
	$(CC) $(CFLAGS) $(CLIENT_OBJ)  -o $(CLIENT_EXEC)  

$(SERVER_EXEC): $(SERVER_OBJ)  $(TESTS_OBJ) $(TESTS_HDR) 
	$(CC) $(CFLAGS) $(TESTS_OBJ) $(SERVER_OBJ) -o $(SERVER_EXEC) $(TESTS_HDR)


$(CLIENT_OBJ): $(CLIENT_SRC)  
	$(CC) $(CFLAGS) -c $(CLIENT_SRC) -o $(CLIENT_OBJ) 

$(SERVER_OBJ): $(SERVER_SRC)
	$(CC) $(CFLAGS) -c $(SERVER_SRC)  -o $(SERVER_OBJ) 

$(TESTS_OBJ): $(TESTS_SRC) 
	$(CC) $(CFLAGS) -c $(TESTS_SRC)  


clean:
	rm -f $(CLIENT_OBJ) $(SERVER_OBJ) $(TESTS_OBJ) $(EXEC)


.PHONY: all